name: Update Portfoliov2

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Portfolio Script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          TABLE_ID: ${{ secrets.TABLE_ID }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        run: python main.py
